server:
  port: 8084

spring:
  application:
    name: BookOrderService
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
    eureka:
      instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_db
    username: my_user
    password: 12345
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate